### PR TITLE
Fix IgnoreUnmatchedProperties for map types

### LINKED ISSUE #90: Ignore unmapped properties in YAML
Given a YAML file that contains more information than the object deserializing it, the current implementation will throw an exception because there is not a corresponding object property for all properties in the YAML file.

### PR DESCRIPTION
**Pull request by bdovaz**
Fixes #90

### CODE REVIEW

**Comment by bdovaz** [comment]
@xoofx I think I fixed all the bugs but now I get a GitHub API rate limit error:

image

**Comment by xoofx** [comment]
Thanks!

**Comment by xoofx** [comment]
> I think I fixed all the errors but now I get a GitHub API rate limit error:

There was a bug in dotnet-releaser that were matching old version of SharpYaml back in 2013 (fixed [here](https://github.com/xoofx/dotnet-releaser/commit/038d89612d5b71158b654dc5130b407acd902ee4)), and so it was trying to retrieve the entire commit history. 

I will retry it later to see if I can publish it.

**Comment by bdovaz** [comment]
Ok thank you and please publish a new SharpYaml NuGet version.

Thanks!

**Comment by bdovaz** [comment]
@xoofx the limit is per hour: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-github_token-in-github-actions

You can try relaunching the workflow: https://github.com/xoofx/SharpYaml/actions/runs/7881903639

I would do it myself but I don't have permissions.

Thanks!

**Comment by bdovaz** [comment]
Thanks @xoofx! Already available!

Today I'm testing this new version thoroughly to see if all my use cases have been solved with this fix and if I see anything I'll create PR quickly.

**Pull request merged**
