### PR TITLE
Support public properties with non-public setters

### PR DESCRIPTION
**Pull request by uwx**
Currently the library will ignore the setter on properties like:
```cs
public string ExampleProperty { get; private set; }
```
This means the property won't be serialized (for some reason) or deserialized. This happens because the code for PropertyDescriptor relies on `MemberDescriptorBase.IsPublic` to be passed to `GetSetMethod` while in reality the property can be public but have a non-public setter.

I simply changed the check so that the `nonPublic` argument is always true. According to the table on [MSDN](https://msdn.microsoft.com/en-us/library/scfx0019(v=vs.110).aspx#Anchor_0) this works fine for both public and non-public setters.

I tested against both the version on NuGet and at 1743b8a78de7756a5b5aca7e297ca83bfdf5c86b, and the behavior is the same.

Cheers,
uwx

### CODE REVIEW

**Comment by xoofx** [comment]
It is by design. Allowing private setter would be a breaking change. It would be possible to allow it if you have a specific attribute on the said property and/or this is made entirely optional (and disabled by default)

**Comment by uwx** [comment]
Fair enough, if I made it an option on the serializer (and fixed the tests) would it be acceptable? If not feel free to close this pull request.

**Comment by xoofx** [comment]
> Fair enough, if I made it an option on the serializer (and fixed the tests) would it be acceptable? If not feel free to close this pull request.

Yes that's ok to have an option in the serializer settings (off by default for private fields).

**Comment by uwx** [comment]
Alright, I've implemented it as a setting `SerializerSettings.RespectPrivateSetters` (false by default) and added relevant tests for it.

**Comment by xoofx** [comment]
Thanks!

**Pull request merged**
